import { League, Team, Game, Analyst, Pick, Post, LeaderboardEntry } from './types';

export const leagues: League[] = [
  { id: 'nfl', name: 'National Football League', shortName: 'NFL', color: '#013369', emoji: '🏈' },
  { id: 'nba', name: 'National Basketball Association', shortName: 'NBA', color: '#17408B', emoji: '🏀' },
  { id: 'mlb', name: 'Major League Baseball', shortName: 'MLB', color: '#002D72', emoji: '⚾' },
  { id: 'nhl', name: 'National Hockey League', shortName: 'NHL', color: '#000000', emoji: '🏒' },
  { id: 'soccer', name: 'Soccer', shortName: 'Soccer', color: '#00A550', emoji: '⚽' },
  { id: 'world-cup', name: 'FIFA World Cup', shortName: 'World Cup', color: '#00A550', emoji: '⚽' },
  { id: 'tennis', name: 'Tennis', shortName: 'Tennis', color: '#C9FF3D', emoji: '🎾' },
];

export const teams: Team[] = [
  { id: 'kc', leagueId: 'nfl', name: 'Kansas City Chiefs', shortName: 'KC', record: '12-4', emoji: '🏈' },
  { id: 'sf', leagueId: 'nfl', name: 'San Francisco 49ers', shortName: 'SF', record: '12-5', emoji: '🏈' },
  { id: 'buf', leagueId: 'nfl', name: 'Buffalo Bills', shortName: 'BUF', record: '11-6', emoji: '🏈' },
  { id: 'dal', leagueId: 'nfl', name: 'Dallas Cowboys', shortName: 'DAL', record: '12-5', emoji: '🏈' },
  { id: 'bos', leagueId: 'nba', name: 'Boston Celtics', shortName: 'BOS', record: '47-10', emoji: '🏀' },
  { id: 'den', leagueId: 'nba', name: 'Denver Nuggets', shortName: 'DEN', record: '40-17', emoji: '🏀' },
  { id: 'lal', leagueId: 'nba', name: 'Los Angeles Lakers', shortName: 'LAL', record: '35-22', emoji: '🏀' },
  { id: 'mil', leagueId: 'nba', name: 'Milwaukee Bucks', shortName: 'MIL', record: '38-19', emoji: '🏀' },
  { id: 'nyy', leagueId: 'mlb', name: 'New York Yankees', shortName: 'NYY', record: '82-50', emoji: '⚾' },
  { id: 'lad', leagueId: 'mlb', name: 'Los Angeles Dodgers', shortName: 'LAD', record: '88-44', emoji: '⚾' },
  { id: 'atl', leagueId: 'mlb', name: 'Atlanta Braves', shortName: 'ATL', record: '80-52', emoji: '⚾' },
  { id: 'hou', leagueId: 'mlb', name: 'Houston Astros', shortName: 'HOU', record: '78-54', emoji: '⚾' },
  { id: 'vgk', leagueId: 'nhl', name: 'Vegas Golden Knights', shortName: 'VGK', record: '35-18-5', emoji: '🏒' },
  { id: 'col', leagueId: 'nhl', name: 'Colorado Avalanche', shortName: 'COL', record: '33-20-4', emoji: '🏒' },
  { id: 'bos_nhl', leagueId: 'nhl', name: 'Boston Bruins', shortName: 'BOS', record: '36-15-7', emoji: '🏒' },
  { id: 'edm', leagueId: 'nhl', name: 'Edmonton Oilers', shortName: 'EDM', record: '34-18-6', emoji: '🏒' },
  { id: 'rma', leagueId: 'soccer', name: 'Real Madrid', shortName: 'RMA', record: '18-3-2', emoji: '⚽' },
  { id: 'mci', leagueId: 'soccer', name: 'Manchester City', shortName: 'MCI', record: '17-3-3', emoji: '⚽' },
  { id: 'bar', leagueId: 'soccer', name: 'Barcelona', shortName: 'BAR', record: '16-4-3', emoji: '⚽' },
  { id: 'liv', leagueId: 'soccer', name: 'Liverpool', shortName: 'LIV', record: '16-5-2', emoji: '⚽' },
];

export const games: Game[] = [
  {
    id: 'g1', leagueId: 'nfl', homeTeamId: 'kc', awayTeamId: 'buf',
    homeTeamName: 'Kansas City Chiefs', awayTeamName: 'Buffalo Bills',
    homeTeamRecord: '12-4', awayTeamRecord: '11-6',
    homeScore: 27, awayScore: 24, status: 'final', date: '2024-01-21', time: '4:25 PM',
    homeWinProbability: 62, awayWinProbability: 38,
    recentFormHome: ['W', 'W', 'L', 'W', 'W'], recentFormAway: ['W', 'L', 'W', 'W', 'L'],
    keyTrend: 'Chiefs unbeaten at Arrowhead in playoffs since 2019', odds: 'KC -3.5',
  },
  {
    id: 'g2', leagueId: 'nfl', homeTeamId: 'sf', awayTeamId: 'dal',
    homeTeamName: 'San Francisco 49ers', awayTeamName: 'Dallas Cowboys',
    homeTeamRecord: '12-5', awayTeamRecord: '12-5',
    homeScore: 0, awayScore: 0, status: 'upcoming', date: '2024-01-28', time: '6:30 PM',
    homeWinProbability: 58, awayWinProbability: 42,
    recentFormHome: ['W', 'W', 'W', 'L', 'W'], recentFormAway: ['W', 'W', 'L', 'W', 'W'],
    keyTrend: '49ers 8-1 SU at home this season', odds: 'SF -4.0',
  },
  {
    id: 'g3', leagueId: 'nba', homeTeamId: 'bos', awayTeamId: 'den',
    homeTeamName: 'Boston Celtics', awayTeamName: 'Denver Nuggets',
    homeTeamRecord: '47-10', awayTeamRecord: '40-17',
    homeScore: 112, awayScore: 107, status: 'live', date: '2024-01-25', time: '7:30 PM',
    homeWinProbability: 71, awayWinProbability: 29,
    recentFormHome: ['W', 'W', 'W', 'W', 'L'], recentFormAway: ['L', 'W', 'W', 'L', 'W'],
    keyTrend: 'Celtics on 7-game win streak at home', odds: 'BOS -6.5',
  },
  {
    id: 'g4', leagueId: 'nba', homeTeamId: 'lal', awayTeamId: 'mil',
    homeTeamName: 'Los Angeles Lakers', awayTeamName: 'Milwaukee Bucks',
    homeTeamRecord: '35-22', awayTeamRecord: '38-19',
    homeScore: 0, awayScore: 0, status: 'upcoming', date: '2024-01-26', time: '9:00 PM',
    homeWinProbability: 45, awayWinProbability: 55,
    recentFormHome: ['L', 'W', 'L', 'W', 'W'], recentFormAway: ['W', 'W', 'L', 'W', 'W'],
    keyTrend: 'Bucks 5-1 ATS in last 6 road games', odds: 'MIL -1.5',
  },
  {
    id: 'g5', leagueId: 'mlb', homeTeamId: 'lad', awayTeamId: 'nyy',
    homeTeamName: 'Los Angeles Dodgers', awayTeamName: 'New York Yankees',
    homeTeamRecord: '88-44', awayTeamRecord: '82-50',
    homeScore: 5, awayScore: 3, status: 'final', date: '2024-01-20', time: '7:10 PM',
    homeWinProbability: 60, awayWinProbability: 40,
    recentFormHome: ['W', 'W', 'W', 'L', 'W'], recentFormAway: ['L', 'W', 'L', 'W', 'W'],
    keyTrend: 'Dodgers 12-3 in last 15 home games', odds: 'LAD -1.5',
  },
  {
    id: 'g6', leagueId: 'mlb', homeTeamId: 'atl', awayTeamId: 'hou',
    homeTeamName: 'Atlanta Braves', awayTeamName: 'Houston Astros',
    homeTeamRecord: '80-52', awayTeamRecord: '78-54',
    homeScore: 0, awayScore: 0, status: 'upcoming', date: '2024-01-29', time: '4:05 PM',
    homeWinProbability: 53, awayWinProbability: 47,
    recentFormHome: ['W', 'L', 'W', 'W', 'L'], recentFormAway: ['W', 'W', 'L', 'W', 'L'],
    keyTrend: 'Braves have won 8 of last 10 vs Astros', odds: 'ATL -110',
  },
  {
    id: 'g7', leagueId: 'nhl', homeTeamId: 'vgk', awayTeamId: 'col',
    homeTeamName: 'Vegas Golden Knights', awayTeamName: 'Colorado Avalanche',
    homeTeamRecord: '35-18-5', awayTeamRecord: '33-20-4',
    homeScore: 4, awayScore: 2, status: 'final', date: '2024-01-22', time: '10:00 PM',
    homeWinProbability: 57, awayWinProbability: 43,
    recentFormHome: ['W', 'W', 'L', 'W', 'W'], recentFormAway: ['L', 'W', 'W', 'L', 'W'],
    keyTrend: 'Golden Knights 6-2 at T-Mobile Arena', odds: 'VGK -130',
  },
  {
    id: 'g8', leagueId: 'nhl', homeTeamId: 'bos_nhl', awayTeamId: 'edm',
    homeTeamName: 'Boston Bruins', awayTeamName: 'Edmonton Oilers',
    homeTeamRecord: '36-15-7', awayTeamRecord: '34-18-6',
    homeScore: 2, awayScore: 2, status: 'live', date: '2024-01-25', time: '7:00 PM',
    homeWinProbability: 52, awayWinProbability: 48,
    recentFormHome: ['W', 'W', 'W', 'L', 'W'], recentFormAway: ['W', 'L', 'W', 'W', 'L'],
    keyTrend: 'Bruins best home record in NHL', odds: 'BOS -115',
  },
  {
    id: 'g9', leagueId: 'soccer', homeTeamId: 'rma', awayTeamId: 'mci',
    homeTeamName: 'Real Madrid', awayTeamName: 'Manchester City',
    homeTeamRecord: '18-3-2', awayTeamRecord: '17-3-3',
    homeScore: 1, awayScore: 1, status: 'final', date: '2024-01-17', time: '3:00 PM',
    homeWinProbability: 50, awayWinProbability: 50,
    recentFormHome: ['W', 'D', 'W', 'W', 'L'], recentFormAway: ['W', 'W', 'D', 'L', 'W'],
    keyTrend: 'Clasico all-time: tied series at Bernabeu', odds: 'Draw +240',
  },
  {
    id: 'g10', leagueId: 'soccer', homeTeamId: 'bar', awayTeamId: 'liv',
    homeTeamName: 'Barcelona', awayTeamName: 'Liverpool',
    homeTeamRecord: '16-4-3', awayTeamRecord: '16-5-2',
    homeScore: 0, awayScore: 0, status: 'upcoming', date: '2024-02-01', time: '8:00 PM',
    homeWinProbability: 48, awayWinProbability: 52,
    recentFormHome: ['W', 'W', 'L', 'W', 'W'], recentFormAway: ['W', 'W', 'W', 'L', 'W'],
    keyTrend: 'Liverpool unbeaten in last 5 European aways', odds: 'LIV +105',
  },
  {
    id: 'g11', leagueId: 'nfl', homeTeamId: 'buf', awayTeamId: 'sf',
    homeTeamName: 'Buffalo Bills', awayTeamName: 'San Francisco 49ers',
    homeTeamRecord: '11-6', awayTeamRecord: '12-5',
    homeScore: 31, awayScore: 17, status: 'final', date: '2024-01-14', time: '1:00 PM',
    homeWinProbability: 55, awayWinProbability: 45,
    recentFormHome: ['W', 'W', 'W', 'L', 'W'], recentFormAway: ['L', 'W', 'W', 'W', 'L'],
    keyTrend: 'Allen throws for 300+ in 4 straight home games', odds: 'BUF -2.5',
  },
  {
    id: 'g12', leagueId: 'nba', homeTeamId: 'mil', awayTeamId: 'bos',
    homeTeamName: 'Milwaukee Bucks', awayTeamName: 'Boston Celtics',
    homeTeamRecord: '38-19', awayTeamRecord: '47-10',
    homeScore: 99, awayScore: 118, status: 'final', date: '2024-01-18', time: '8:00 PM',
    homeWinProbability: 40, awayWinProbability: 60,
    recentFormHome: ['L', 'W', 'L', 'W', 'L'], recentFormAway: ['W', 'W', 'W', 'W', 'W'],
    keyTrend: 'Celtics beat Bucks in 5 of last 6 meetings', odds: 'BOS -3.0',
  },
  {
    id: 'g13', leagueId: 'mlb', homeTeamId: 'nyy', awayTeamId: 'atl',
    homeTeamName: 'New York Yankees', awayTeamName: 'Atlanta Braves',
    homeTeamRecord: '82-50', awayTeamRecord: '80-52',
    homeScore: 7, awayScore: 4, status: 'final', date: '2024-01-19', time: '7:05 PM',
    homeWinProbability: 56, awayWinProbability: 44,
    recentFormHome: ['W', 'W', 'L', 'W', 'W'], recentFormAway: ['W', 'L', 'W', 'L', 'W'],
    keyTrend: 'Yankees 9-2 at home in day games this season', odds: 'NYY -150',
  },
  {
    id: 'g14', leagueId: 'nhl', homeTeamId: 'col', awayTeamId: 'bos_nhl',
    homeTeamName: 'Colorado Avalanche', awayTeamName: 'Boston Bruins',
    homeTeamRecord: '33-20-4', awayTeamRecord: '36-15-7',
    homeScore: 0, awayScore: 0, status: 'upcoming', date: '2024-01-30', time: '9:00 PM',
    homeWinProbability: 49, awayWinProbability: 51,
    recentFormHome: ['W', 'L', 'W', 'W', 'L'], recentFormAway: ['W', 'W', 'L', 'W', 'W'],
    keyTrend: 'MacKinnon hot streak: 12 points in last 7 games', odds: 'COL +110',
  },
  {
    id: 'g15', leagueId: 'soccer', homeTeamId: 'mci', awayTeamId: 'rma',
    homeTeamName: 'Manchester City', awayTeamName: 'Real Madrid',
    homeTeamRecord: '17-3-3', awayTeamRecord: '18-3-2',
    homeScore: 0, awayScore: 0, status: 'upcoming', date: '2024-02-06', time: '8:00 PM',
    homeWinProbability: 54, awayWinProbability: 46,
    recentFormHome: ['W', 'W', 'W', 'D', 'W'], recentFormAway: ['W', 'L', 'W', 'W', 'D'],
    keyTrend: 'Man City 11-2-1 at Etihad this season', odds: 'MCI -130',
  },
];

export const analysts: Analyst[] = [
  { id: 'a1', name: 'Marcus Thompson', bio: 'Former NFL scout with 15 years of experience. Specializes in offensive line analytics and quarterback performance metrics.', favoriteLeagues: ['NFL', 'NCAA'], followers: 12400, totalPicks: 340, winRate: 72, performanceScore: 88, isFollowing: false },
  { id: 'a2', name: 'Sofia Reyes', bio: 'Data scientist turned sports analyst. Known for advanced statistical models and contrarian picks that beat the market.', favoriteLeagues: ['NBA', 'NFL'], followers: 9800, totalPicks: 280, winRate: 69, performanceScore: 84, isFollowing: true },
  { id: 'a3', name: 'James "The Hammer" Harrington', bio: 'Hockey insider with connections across all 32 NHL teams. Specializes in goalie matchups and power play efficiency.', favoriteLeagues: ['NHL', 'Soccer'], followers: 7600, totalPicks: 210, winRate: 67, performanceScore: 79, isFollowing: false },
  { id: 'a4', name: 'Priya Nair', bio: 'MLB statistician and Sabermetrics expert. Focuses on pitcher fatigue, park factors, and bullpen usage trends.', favoriteLeagues: ['MLB', 'Soccer'], followers: 6200, totalPicks: 195, winRate: 71, performanceScore: 83, isFollowing: false },
  { id: 'a5', name: 'Derek "Fast Break" Wilson', bio: 'Former D1 basketball player and ESPN contributor. Specializes in pace-of-play analytics and NBA player prop bets.', favoriteLeagues: ['NBA', 'NCAA'], followers: 15300, totalPicks: 420, winRate: 65, performanceScore: 76, isFollowing: true },
  { id: 'a6', name: 'Elena Kovacs', bio: 'European football analyst with UEFA certification. Expert in tactical formations, pressing intensity, and set piece analysis.', favoriteLeagues: ['Soccer', 'NFL'], followers: 8900, totalPicks: 255, winRate: 68, performanceScore: 80, isFollowing: false },
  { id: 'a7', name: 'Tony Salvatore', bio: 'Veteran Vegas handicapper with 20 years in the industry. Sharp money tracker and line movement specialist.', favoriteLeagues: ['NFL', 'NBA', 'MLB'], followers: 22100, totalPicks: 580, winRate: 61, performanceScore: 73, isFollowing: false },
  { id: 'a8', name: 'Aisha Johnson', bio: 'Sports journalist turned analyst. Covers the intersection of injuries, team chemistry, and situational handicapping.', favoriteLeagues: ['NBA', 'NFL'], followers: 11200, totalPicks: 310, winRate: 66, performanceScore: 78, isFollowing: false },
  { id: 'a9', name: 'Carlos Mendez', bio: 'Quant analyst specializing in machine learning models for sports prediction. MIT graduate with a track record in MLB and NHL.', favoriteLeagues: ['MLB', 'NHL'], followers: 5400, totalPicks: 160, winRate: 74, performanceScore: 87, isFollowing: true },
  { id: 'a10', name: 'Rachel "The Oracle" Kim', bio: 'Consensus builder and trend identifier. Known for identifying public betting traps and fading inflated favorites.', favoriteLeagues: ['NFL', 'NBA', 'Soccer'], followers: 18700, totalPicks: 490, winRate: 63, performanceScore: 75, isFollowing: false },
];

export const picks: Pick[] = [
  { id: 'p1', analystId: 'a1', analystName: 'Marcus Thompson', leagueId: 'nfl', gameId: 'g1', gameDescription: 'Chiefs vs Bills', prediction: 'Chiefs -3.5', confidence: 8, reasoning: 'Mahomes historically dominates in playoff settings at home. Bills secondary has been vulnerable to quick releases. Chiefs OL matchup is favorable.', result: 'win', likes: 234, comments: 45, createdAt: '2024-01-20T14:00:00Z' },
  { id: 'p2', analystId: 'a2', analystName: 'Sofia Reyes', leagueId: 'nba', gameId: 'g3', gameDescription: 'Celtics vs Nuggets', prediction: 'Celtics -6.5', confidence: 7, reasoning: "Boston's defensive rating at home is elite this season. Jokic needs Jamal Murray who is listed as questionable. Tatum has been unstoppable in the Garden.", result: 'win', likes: 189, comments: 32, createdAt: '2024-01-24T18:00:00Z' },
  { id: 'p3', analystId: 'a3', analystName: 'James Harrington', leagueId: 'nhl', gameId: 'g7', gameDescription: 'Golden Knights vs Avalanche', prediction: 'Golden Knights -130', confidence: 9, reasoning: 'Robin Lehner back in net after strong practice week. Vegas power play at 31% this month. Colorado missing two top-6 forwards.', result: 'win', likes: 156, comments: 28, createdAt: '2024-01-21T20:00:00Z' },
  { id: 'p4', analystId: 'a4', analystName: 'Priya Nair', leagueId: 'mlb', gameId: 'g5', gameDescription: 'Dodgers vs Yankees', prediction: 'Dodgers -1.5', confidence: 8, reasoning: 'Yamamoto pitching on ideal rest with 5 days off. Yankees starter has a 5.2 ERA in his last 6 road starts. Dodgers lineup is healthy.', result: 'win', likes: 201, comments: 37, createdAt: '2024-01-19T16:00:00Z' },
  { id: 'p5', analystId: 'a5', analystName: 'Derek Wilson', leagueId: 'nba', gameId: 'g4', gameDescription: 'Lakers vs Bucks', prediction: 'Bucks -1.5', confidence: 6, reasoning: 'Giannis back at full health and Bucks play better on the road with less crowd pressure. Lakers missing Anthony Davis in lineup report.', result: 'pending', likes: 98, comments: 22, createdAt: '2024-01-25T10:00:00Z' },
  { id: 'p6', analystId: 'a6', analystName: 'Elena Kovacs', leagueId: 'soccer', gameId: 'g9', gameDescription: 'Real Madrid vs Man City', prediction: 'Draw +240', confidence: 7, reasoning: "Both teams in form but will be cautious in first leg. Zidane's squad has drawn 4 of last 6 home games vs elite opposition. Value in the draw price.", result: 'win', likes: 312, comments: 67, createdAt: '2024-01-16T14:00:00Z' },
  { id: 'p7', analystId: 'a7', analystName: 'Tony Salvatore', leagueId: 'nfl', gameId: 'g2', gameDescription: '49ers vs Cowboys', prediction: '49ers -4.0', confidence: 7, reasoning: 'Sharp money has been hammering the 49ers since line opened at -3. Purdy at home is virtually unbeatable. Dallas O-line vs SF pass rush is a disaster.', result: 'pending', likes: 445, comments: 89, createdAt: '2024-01-26T09:00:00Z' },
  { id: 'p8', analystId: 'a8', analystName: 'Aisha Johnson', leagueId: 'nba', gameId: 'g12', gameDescription: 'Bucks vs Celtics', prediction: 'Celtics -3.0', confidence: 8, reasoning: 'Bucks have lost Khris Middleton to injury. Celtics are playing their best basketball of the season with a team-high net rating of +12.4.', result: 'win', likes: 167, comments: 41, createdAt: '2024-01-17T20:00:00Z' },
  { id: 'p9', analystId: 'a9', analystName: 'Carlos Mendez', leagueId: 'mlb', gameId: 'g13', gameDescription: 'Yankees vs Braves', prediction: 'Yankees -150', confidence: 9, reasoning: 'My model projects 61% win probability for NYY. Cole on the mound with a 1.8 ERA at home. Braves batting .198 vs right-handed pitchers this month.', result: 'win', likes: 278, comments: 55, createdAt: '2024-01-18T15:00:00Z' },
  { id: 'p10', analystId: 'a10', analystName: 'Rachel Kim', leagueId: 'nfl', gameId: 'g11', gameDescription: 'Bills vs 49ers', prediction: 'Bills -2.5', confidence: 7, reasoning: 'Public is sleeping on Buffalo. Allen vs the 49ers defense is a great spot given their zone coverage tendencies. Bills have covered in 6 of last 7 home games.', result: 'win', likes: 334, comments: 72, createdAt: '2024-01-13T18:00:00Z' },
  { id: 'p11', analystId: 'a1', analystName: 'Marcus Thompson', leagueId: 'nfl', gameId: 'g2', gameDescription: '49ers vs Cowboys', prediction: 'Under 47.5', confidence: 6, reasoning: "Both defenses are elite. Expect a grind-it-out game. Weather forecast shows 25mph winds at Levi's. Under is 5-1 in 49ers playoff games.", result: 'pending', likes: 156, comments: 29, createdAt: '2024-01-26T11:00:00Z' },
  { id: 'p12', analystId: 'a3', analystName: 'James Harrington', leagueId: 'nhl', gameId: 'g8', gameDescription: 'Bruins vs Oilers', prediction: 'Bruins -115', confidence: 7, reasoning: 'Swayman has been incredible at home with a .932 save percentage. Oilers Draisaitl questionable. Bruins best defensive structure in the league.', result: 'push', likes: 143, comments: 31, createdAt: '2024-01-24T16:00:00Z' },
  { id: 'p13', analystId: 'a2', analystName: 'Sofia Reyes', leagueId: 'nba', gameId: 'g4', gameDescription: 'Lakers vs Bucks', prediction: 'Over 224.5', confidence: 6, reasoning: 'Both teams rank top-8 in pace. LeBron and Giannis always produce high-scoring games. Last 5 meetings averaged 238 combined points.', result: 'pending', likes: 87, comments: 18, createdAt: '2024-01-25T12:00:00Z' },
  { id: 'p14', analystId: 'a5', analystName: 'Derek Wilson', leagueId: 'nba', gameId: 'g3', gameDescription: 'Celtics vs Nuggets', prediction: 'Celtics ML', confidence: 9, reasoning: 'Denver playing 4th game in 6 nights. Boston fresh off a 3-day rest. Celtics home court advantage is worth 4+ points this season.', result: 'win', likes: 221, comments: 48, createdAt: '2024-01-24T17:00:00Z' },
  { id: 'p15', analystId: 'a4', analystName: 'Priya Nair', leagueId: 'mlb', gameId: 'g6', gameDescription: 'Braves vs Astros', prediction: 'Braves -110', confidence: 7, reasoning: "Fried pitching with 5.1 innings of rest. Atlanta's wOBA against lefties is .295 vs Houston's starter's .271. Park factors favor low scoring.", result: 'pending', likes: 112, comments: 24, createdAt: '2024-01-28T10:00:00Z' },
  { id: 'p16', analystId: 'a6', analystName: 'Elena Kovacs', leagueId: 'soccer', gameId: 'g10', gameDescription: 'Barcelona vs Liverpool', prediction: 'Liverpool +105', confidence: 6, reasoning: "Barca missing key central midfielders. Liverpool's front three have 7 UCL away goals this season. Value on Liverpool at slight plus odds.", result: 'pending', likes: 267, comments: 53, createdAt: '2024-01-30T14:00:00Z' },
  { id: 'p17', analystId: 'a7', analystName: 'Tony Salvatore', leagueId: 'nhl', gameId: 'g14', gameDescription: 'Avalanche vs Bruins', prediction: 'Avalanche +110', confidence: 6, reasoning: 'Colorado at home with MacKinnon is dangerous. Line movement from -130 to +110 signals sharp action. Bruins in their 3rd game of 4 in 6 days.', result: 'pending', likes: 189, comments: 35, createdAt: '2024-01-29T15:00:00Z' },
  { id: 'p18', analystId: 'a8', analystName: 'Aisha Johnson', leagueId: 'nfl', gameId: 'g1', gameDescription: 'Chiefs vs Bills', prediction: 'Over 51.5', confidence: 5, reasoning: 'Both offenses lit up last week. Allen will be aggressive to keep pace with Mahomes. Total has gone over in 4 of last 5 Bills playoff games.', result: 'loss', likes: 145, comments: 33, createdAt: '2024-01-20T12:00:00Z' },
  { id: 'p19', analystId: 'a9', analystName: 'Carlos Mendez', leagueId: 'soccer', gameId: 'g15', gameDescription: 'Man City vs Real Madrid', prediction: 'Man City -130', confidence: 8, reasoning: 'My xG model projects City at 1.8 vs Madrid at 1.1. Guardiola at home in UCL knockouts is 14-4. Madrid missing Bellingham for this one.', result: 'pending', likes: 203, comments: 44, createdAt: '2024-02-04T10:00:00Z' },
  { id: 'p20', analystId: 'a10', analystName: 'Rachel Kim', leagueId: 'nba', gameId: 'g12', gameDescription: 'Bucks vs Celtics', prediction: 'Celtics -3 1st Half', confidence: 7, reasoning: 'Boston starts games exceptionally well. Celtics lead at halftime in 72% of home games. Bucks historically slow starters on the road.', result: 'win', likes: 178, comments: 39, createdAt: '2024-01-17T19:00:00Z' },
];

export const posts: Post[] = [
  { id: 'post1', authorId: 'a1', authorName: 'Marcus Thompson', topic: 'Analysis', leagueId: 'nfl', content: "Chiefs offensive line has been one of the most underrated stories of the season. Their pass protection grades are elite and that's going to be crucial in the playoffs. Don't sleep on this unit!", timestamp: '2h ago', commentCount: 23, likes: 145 },
  { id: 'post2', authorId: 'a2', authorName: 'Sofia Reyes', topic: 'Stats', leagueId: 'nba', content: "Looking at the Celtics' defensive rating numbers this season - they're historically good. 106.4 DRTG at home is the best we've seen since the 2016 Warriors. This team is special.", timestamp: '4h ago', commentCount: 31, likes: 198 },
  { id: 'post3', authorId: 'a5', authorName: 'Derek Wilson', topic: 'Hot Take', leagueId: 'nba', content: 'Unpopular opinion: The Nuggets are actually the most dangerous team in the West playoffs because everyone is sleeping on them. Jokic in the 4th quarter is 🐐 behavior.', timestamp: '6h ago', commentCount: 67, likes: 312 },
  { id: 'post4', authorId: 'a4', authorName: 'Priya Nair', topic: 'Injury Watch', leagueId: 'mlb', content: "Keep an eye on Gerrit Cole's pitch count and velocity trends. There's a subtle drop in his fastball spin rate that the public hasn't picked up on yet. Could impact Yankees in big spots.", timestamp: '8h ago', commentCount: 19, likes: 87 },
  { id: 'post5', authorId: 'a6', authorName: 'Elena Kovacs', topic: 'Tactics', leagueId: 'soccer', content: "Guardiola's modified 4-3-3 press is specifically designed to counter Ancelotti's 4-4-2 mid-block. The space behind Madrid's fullbacks will be exploited aggressively. Key tactical battle to watch.", timestamp: '10h ago', commentCount: 44, likes: 267 },
  { id: 'post6', authorId: 'a7', authorName: 'Tony Salvatore', topic: 'Sharp Money', leagueId: 'nfl', content: 'Heavy reverse line movement on the 49ers. Line moved from -4 to -3 despite 78% public on SF. This is a classic steam move indicator. Take note of where the money is really going.', timestamp: '12h ago', commentCount: 56, likes: 389 },
  { id: 'post7', authorId: 'a3', authorName: 'James Harrington', topic: 'Goalie Report', leagueId: 'nhl', content: 'Full goalie report for tonight: Hellebuyck confirmed starting for Winnipeg despite morning skate absence. Binnington is a game-time decision. Varlamov is out for NYI. Plan accordingly!', timestamp: '1h ago', commentCount: 28, likes: 156 },
  { id: 'post8', authorId: 'a8', authorName: 'Aisha Johnson', topic: 'Team News', leagueId: 'nba', content: "Breaking: Damian Lillard has been upgraded to probable for tonight's game. His presence changes the entire Bucks offense - this is a major line mover if confirmed for tip-off.", timestamp: '30m ago', commentCount: 89, likes: 445 },
  { id: 'post9', authorId: 'a9', authorName: 'Carlos Mendez', topic: 'Model Output', leagueId: 'mlb', content: "My ML model had Dodgers as 63.2% win probability against the Yankees, which translates to -171 fair odds. The market had them at -145. That's a clear edge - exactly the kind of spot I look for.", timestamp: '1d ago', commentCount: 34, likes: 234 },
  { id: 'post10', authorId: 'a10', authorName: 'Rachel Kim', topic: 'Betting Market', leagueId: 'nfl', content: 'The Bills are being severely underrated by the public. Buffalo has covered in 6 of their last 7 home games and yet the market is pricing them like a coin flip. I see a massive overlay here.', timestamp: '2d ago', commentCount: 47, likes: 278 },
  { id: 'post11', authorId: 'a2', authorName: 'Sofia Reyes', topic: 'Deep Dive', leagueId: 'nba', content: 'Thread on why assist-to-turnover ratio is the most undervalued stat in NBA betting. Teams with ATR over 2.0 cover the spread 64% of the time vs teams under 1.5. The Celtics at 2.4 are elite.', timestamp: '3d ago', commentCount: 62, likes: 334 },
  { id: 'post12', authorId: 'a6', authorName: 'Elena Kovacs', topic: 'Preview', leagueId: 'soccer', content: "Full tactical preview of Barcelona vs Liverpool is up. Key areas: Xavi's high press vs Klopp's low block, Salah vs Balde in a crucial 1v1, and set piece danger from both teams.", timestamp: '1d ago', commentCount: 38, likes: 201 },
  { id: 'post13', authorId: 'a4', authorName: 'Priya Nair', topic: 'Sabermetrics', leagueId: 'mlb', content: 'FIP vs ERA discrepancy spotlight: Three pitchers whose FIP is 1.5+ runs better than ERA - Eflin, Strider, Gausman. These starters are in for massive ERA regression in their favor. Watch them.', timestamp: '2d ago', commentCount: 25, likes: 167 },
  { id: 'post14', authorId: 'a1', authorName: 'Marcus Thompson', topic: 'Historical', leagueId: 'nfl', content: 'Super Bowl prediction time. Teams with a top-3 rushing offense AND top-5 pass defense have won the Super Bowl 7 of the last 10 years. Guess which two teams fit that profile this year?', timestamp: '4d ago', commentCount: 93, likes: 512 },
  { id: 'post15', authorId: 'a7', authorName: 'Tony Salvatore', topic: 'Weather Impact', leagueId: 'nfl', content: "Wind advisory issued for Sunday's 49ers vs Cowboys game. 22-28mph sustained with gusts to 40mph. Historical data shows totals go under in 71% of games with winds over 20mph. Book it.", timestamp: '5h ago', commentCount: 71, likes: 423 },
];

export const leaderboard: LeaderboardEntry[] = [
  { rank: 1, previousRank: 2, analystId: 'a1', analystName: 'Marcus Thompson', accuracy: 72, totalPicks: 340, followers: 12400, recentPerformance: ['W', 'W', 'W', 'L', 'W'], streak: 3 },
  { rank: 2, previousRank: 1, analystId: 'a9', analystName: 'Carlos Mendez', accuracy: 74, totalPicks: 160, followers: 5400, recentPerformance: ['W', 'W', 'W', 'W', 'L'], streak: 4 },
  { rank: 3, previousRank: 3, analystId: 'a4', analystName: 'Priya Nair', accuracy: 71, totalPicks: 195, followers: 6200, recentPerformance: ['W', 'L', 'W', 'W', 'W'], streak: 2 },
  { rank: 4, previousRank: 6, analystId: 'a2', analystName: 'Sofia Reyes', accuracy: 69, totalPicks: 280, followers: 9800, recentPerformance: ['W', 'W', 'L', 'W', 'W'], streak: 2 },
  { rank: 5, previousRank: 4, analystId: 'a3', analystName: 'James Harrington', accuracy: 67, totalPicks: 210, followers: 7600, recentPerformance: ['W', 'W', 'W', 'L', 'L'], streak: -1 },
  { rank: 6, previousRank: 7, analystId: 'a6', analystName: 'Elena Kovacs', accuracy: 68, totalPicks: 255, followers: 8900, recentPerformance: ['L', 'W', 'W', 'W', 'W'], streak: 3 },
  { rank: 7, previousRank: 5, analystId: 'a8', analystName: 'Aisha Johnson', accuracy: 66, totalPicks: 310, followers: 11200, recentPerformance: ['W', 'L', 'W', 'L', 'W'], streak: 1 },
  { rank: 8, previousRank: 8, analystId: 'a5', analystName: 'Derek Wilson', accuracy: 65, totalPicks: 420, followers: 15300, recentPerformance: ['L', 'W', 'L', 'W', 'W'], streak: 1 },
  { rank: 9, previousRank: 10, analystId: 'a10', analystName: 'Rachel Kim', accuracy: 63, totalPicks: 490, followers: 18700, recentPerformance: ['W', 'W', 'W', 'L', 'W'], streak: 1 },
  { rank: 10, previousRank: 9, analystId: 'a7', analystName: 'Tony Salvatore', accuracy: 61, totalPicks: 580, followers: 22100, recentPerformance: ['L', 'W', 'L', 'W', 'L'], streak: -1 },
];
