import { Analyst, Game, LeaderboardEntry, Pick, Post, Team } from './types';

// ─── Teams ───────────────────────────────────────────────────────────────────

const nflTeams: Record<string, Team> = {
  chiefs: { id: 'chiefs', name: 'Kansas City Chiefs', abbreviation: 'KC', league: 'NFL', record: '11-3', color: '#E31837' },
  eagles: { id: 'eagles', name: 'Philadelphia Eagles', abbreviation: 'PHI', league: 'NFL', record: '10-4', color: '#004C54' },
  bills: { id: 'bills', name: 'Buffalo Bills', abbreviation: 'BUF', league: 'NFL', record: '10-4', color: '#00338D' },
  ravens: { id: 'ravens', name: 'Baltimore Ravens', abbreviation: 'BAL', league: 'NFL', record: '11-3', color: '#241773' },
  cowboys: { id: 'cowboys', name: 'Dallas Cowboys', abbreviation: 'DAL', league: 'NFL', record: '9-5', color: '#003594' },
  niners: { id: 'niners', name: 'San Francisco 49ers', abbreviation: 'SF', league: 'NFL', record: '10-4', color: '#AA0000' },
};

const nbaTeams: Record<string, Team> = {
  celtics: { id: 'celtics', name: 'Boston Celtics', abbreviation: 'BOS', league: 'NBA', record: '28-7', color: '#007A33' },
  nuggets: { id: 'nuggets', name: 'Denver Nuggets', abbreviation: 'DEN', league: 'NBA', record: '25-10', color: '#0E2240' },
  bucks: { id: 'bucks', name: 'Milwaukee Bucks', abbreviation: 'MIL', league: 'NBA', record: '22-13', color: '#00471B' },
  lakers: { id: 'lakers', name: 'Los Angeles Lakers', abbreviation: 'LAL', league: 'NBA', record: '20-15', color: '#552583' },
  thunder: { id: 'thunder', name: 'Oklahoma City Thunder', abbreviation: 'OKC', league: 'NBA', record: '26-9', color: '#007AC1' },
  heat: { id: 'heat', name: 'Miami Heat', abbreviation: 'MIA', league: 'NBA', record: '19-16', color: '#98002E' },
};

const mlbTeams: Record<string, Team> = {
  dodgers: { id: 'dodgers', name: 'Los Angeles Dodgers', abbreviation: 'LAD', league: 'MLB', record: '98-64', color: '#005A9C' },
  braves: { id: 'braves', name: 'Atlanta Braves', abbreviation: 'ATL', league: 'MLB', record: '89-73', color: '#CE1141' },
  astros: { id: 'astros', name: 'Houston Astros', abbreviation: 'HOU', league: 'MLB', record: '90-72', color: '#002D62' },
  yankees: { id: 'yankees', name: 'New York Yankees', abbreviation: 'NYY', league: 'MLB', record: '94-68', color: '#0C2340' },
  rangers: { id: 'rangers', name: 'Texas Rangers', abbreviation: 'TEX', league: 'MLB', record: '95-67', color: '#003278' },
};

const nhlTeams: Record<string, Team> = {
  bruins: { id: 'bruins', name: 'Boston Bruins', abbreviation: 'BOS', league: 'NHL', record: '24-9-3', color: '#FFB81C' },
  panthers: { id: 'panthers', name: 'Florida Panthers', abbreviation: 'FLA', league: 'NHL', record: '23-11-2', color: '#041E42' },
  avalanche: { id: 'avalanche', name: 'Colorado Avalanche', abbreviation: 'COL', league: 'NHL', record: '21-13-2', color: '#6F263D' },
  rangers_nhl: { id: 'rangers_nhl', name: 'New York Rangers', abbreviation: 'NYR', league: 'NHL', record: '22-12-3', color: '#0038A8' },
  oilers: { id: 'oilers', name: 'Edmonton Oilers', abbreviation: 'EDM', league: 'NHL', record: '20-15-1', color: '#FF4C00' },
};

const soccerTeams: Record<string, Team> = {
  manCity: { id: 'manCity', name: 'Manchester City', abbreviation: 'MCI', league: 'Soccer', record: '14-3-2', color: '#6CABDD' },
  arsenal: { id: 'arsenal', name: 'Arsenal', abbreviation: 'ARS', league: 'Soccer', record: '13-2-4', color: '#EF0107' },
  liverpool: { id: 'liverpool', name: 'Liverpool', abbreviation: 'LIV', league: 'Soccer', record: '12-4-3', color: '#C8102E' },
  chelsea: { id: 'chelsea', name: 'Chelsea', abbreviation: 'CHE', league: 'Soccer', record: '10-5-4', color: '#034694' },
  realMadrid: { id: 'realMadrid', name: 'Real Madrid', abbreviation: 'RMA', league: 'Soccer', record: '15-2-2', color: '#FEBE10' },
  barcelona: { id: 'barcelona', name: 'FC Barcelona', abbreviation: 'FCB', league: 'Soccer', record: '13-3-3', color: '#A50044' },
};

// ─── Games ────────────────────────────────────────────────────────────────────

export const mockGames: Game[] = [
  // NFL
  {
    id: 'nfl-1',
    league: 'NFL',
    homeTeam: nflTeams.chiefs,
    awayTeam: nflTeams.ravens,
    date: '2024-12-25',
    time: '4:30 PM ET',
    status: 'upcoming',
    homeWinProbability: 0.58,
    homeRecentForm: 'WWLWW',
    awayRecentForm: 'WWWLW',
    keyTrend: 'Chiefs are 8-2 ATS at home this season',
    venue: 'Arrowhead Stadium',
  },
  {
    id: 'nfl-2',
    league: 'NFL',
    homeTeam: nflTeams.eagles,
    awayTeam: nflTeams.cowboys,
    date: '2024-12-22',
    time: '1:00 PM ET',
    status: 'live',
    homeScore: 24,
    awayScore: 17,
    homeWinProbability: 0.72,
    homeRecentForm: 'WWWLW',
    awayRecentForm: 'LWWLW',
    keyTrend: 'Eagles averaging 34 pts/game at home',
    venue: 'Lincoln Financial Field',
  },
  {
    id: 'nfl-3',
    league: 'NFL',
    homeTeam: nflTeams.bills,
    awayTeam: nflTeams.niners,
    date: '2024-12-21',
    time: '8:20 PM ET',
    status: 'final',
    homeScore: 27,
    awayScore: 35,
    homeWinProbability: 0.44,
    homeRecentForm: 'WWLWL',
    awayRecentForm: 'WWWWL',
    keyTrend: '49ers QB Purdy has 7 TD passes last 3 games',
    venue: 'Highmark Stadium',
  },
  {
    id: 'nfl-4',
    league: 'NFL',
    homeTeam: nflTeams.ravens,
    awayTeam: nflTeams.niners,
    date: '2024-12-29',
    time: '4:25 PM ET',
    status: 'upcoming',
    homeWinProbability: 0.53,
    homeRecentForm: 'WWWLW',
    awayRecentForm: 'WWWWL',
    keyTrend: 'Ravens Lamar Jackson MVP frontrunner with 4200+ pass yards',
    venue: 'M&T Bank Stadium',
  },
  {
    id: 'nfl-5',
    league: 'NFL',
    homeTeam: nflTeams.chiefs,
    awayTeam: nflTeams.bills,
    date: '2024-12-15',
    time: '4:25 PM ET',
    status: 'final',
    homeScore: 30,
    awayScore: 21,
    homeWinProbability: 0.61,
    homeRecentForm: 'WWLWW',
    awayRecentForm: 'WWWLW',
    keyTrend: 'Mahomes is 7-1 against Bills in regular season',
    venue: 'Arrowhead Stadium',
  },
  // NBA
  {
    id: 'nba-1',
    league: 'NBA',
    homeTeam: nbaTeams.celtics,
    awayTeam: nbaTeams.nuggets,
    date: '2024-12-22',
    time: '7:30 PM ET',
    status: 'upcoming',
    homeWinProbability: 0.62,
    homeRecentForm: 'WWWLW',
    awayRecentForm: 'WLWWW',
    keyTrend: 'Celtics lead NBA in 3PT% at 39.8%',
    venue: 'TD Garden',
  },
  {
    id: 'nba-2',
    league: 'NBA',
    homeTeam: nbaTeams.thunder,
    awayTeam: nbaTeams.lakers,
    date: '2024-12-21',
    time: '10:00 PM ET',
    status: 'live',
    homeScore: 78,
    awayScore: 71,
    homeWinProbability: 0.68,
    homeRecentForm: 'WWWWL',
    awayRecentForm: 'LWLWW',
    keyTrend: 'SGA averaging 32.4 PPG at home this month',
    venue: 'Paycom Center',
  },
  {
    id: 'nba-3',
    league: 'NBA',
    homeTeam: nbaTeams.bucks,
    awayTeam: nbaTeams.heat,
    date: '2024-12-20',
    time: '8:00 PM ET',
    status: 'final',
    homeScore: 121,
    awayScore: 114,
    homeWinProbability: 0.57,
    homeRecentForm: 'WLWWW',
    awayRecentForm: 'LWLWL',
    keyTrend: 'Giannis posted 35 pts, 14 reb in last meeting',
    venue: 'Fiserv Forum',
  },
  {
    id: 'nba-4',
    league: 'NBA',
    homeTeam: nbaTeams.lakers,
    awayTeam: nbaTeams.celtics,
    date: '2024-12-28',
    time: '8:30 PM ET',
    status: 'upcoming',
    homeWinProbability: 0.41,
    homeRecentForm: 'LWLWW',
    awayRecentForm: 'WWWLW',
    keyTrend: 'Celtics 12-3 against Western Conference this season',
    venue: 'Crypto.com Arena',
  },
  {
    id: 'nba-5',
    league: 'NBA',
    homeTeam: nbaTeams.nuggets,
    awayTeam: nbaTeams.bucks,
    date: '2024-12-26',
    time: '9:00 PM ET',
    status: 'upcoming',
    homeWinProbability: 0.55,
    homeRecentForm: 'WLWWW',
    awayRecentForm: 'WLWWW',
    keyTrend: 'Jokic triple-double streak at 6 games and counting',
    venue: 'Ball Arena',
  },
  // MLB
  {
    id: 'mlb-1',
    league: 'MLB',
    homeTeam: mlbTeams.dodgers,
    awayTeam: mlbTeams.yankees,
    date: '2024-10-25',
    time: '8:08 PM ET',
    status: 'final',
    homeScore: 6,
    awayScore: 3,
    homeWinProbability: 0.64,
    homeRecentForm: 'WWWLW',
    awayRecentForm: 'WLWWL',
    keyTrend: 'Dodgers rotation ERA under 2.50 in playoffs',
    venue: 'Dodger Stadium',
  },
  {
    id: 'mlb-2',
    league: 'MLB',
    homeTeam: mlbTeams.braves,
    awayTeam: mlbTeams.astros,
    date: '2024-10-26',
    time: '5:07 PM ET',
    status: 'final',
    homeScore: 4,
    awayScore: 7,
    homeWinProbability: 0.49,
    homeRecentForm: 'LWWWL',
    awayRecentForm: 'WWLWW',
    keyTrend: 'Astros bullpen holding opponents to .198 batting average',
    venue: 'Truist Park',
  },
  {
    id: 'mlb-3',
    league: 'MLB',
    homeTeam: mlbTeams.rangers,
    awayTeam: mlbTeams.dodgers,
    date: '2024-10-27',
    time: '8:03 PM ET',
    status: 'final',
    homeScore: 2,
    awayScore: 5,
    homeWinProbability: 0.46,
    homeRecentForm: 'WLWLW',
    awayRecentForm: 'WWWLW',
    keyTrend: 'Dodgers Ohtani batting .380 in elimination games',
    venue: 'Globe Life Field',
  },
  {
    id: 'mlb-4',
    league: 'MLB',
    homeTeam: mlbTeams.yankees,
    awayTeam: mlbTeams.braves,
    date: '2024-10-30',
    time: '7:08 PM ET',
    status: 'upcoming',
    homeWinProbability: 0.52,
    homeRecentForm: 'WLWWL',
    awayRecentForm: 'LWWWL',
    keyTrend: 'Yankees Judge hitting .441 against LHP this postseason',
    venue: 'Yankee Stadium',
  },
  {
    id: 'mlb-5',
    league: 'MLB',
    homeTeam: mlbTeams.astros,
    awayTeam: mlbTeams.rangers,
    date: '2024-10-31',
    time: '8:07 PM ET',
    status: 'upcoming',
    homeWinProbability: 0.58,
    homeRecentForm: 'WWLWW',
    awayRecentForm: 'WLWLW',
    keyTrend: 'Astros 18-6 at home in October over last 3 years',
    venue: 'Minute Maid Park',
  },
  // NHL
  {
    id: 'nhl-1',
    league: 'NHL',
    homeTeam: nhlTeams.bruins,
    awayTeam: nhlTeams.panthers,
    date: '2024-12-21',
    time: '7:00 PM ET',
    status: 'live',
    homeScore: 2,
    awayScore: 1,
    homeWinProbability: 0.58,
    homeRecentForm: 'WWWLW',
    awayRecentForm: 'WLWWW',
    keyTrend: 'Bruins PP% of 28.4 leads the Eastern Conference',
    venue: 'TD Garden',
  },
  {
    id: 'nhl-2',
    league: 'NHL',
    homeTeam: nhlTeams.avalanche,
    awayTeam: nhlTeams.oilers,
    date: '2024-12-22',
    time: '9:00 PM ET',
    status: 'upcoming',
    homeWinProbability: 0.54,
    homeRecentForm: 'WLWWL',
    awayRecentForm: 'WWLWW',
    keyTrend: 'Avalanche MacKinnon 12 pts in last 8 games',
    venue: 'Ball Arena',
  },
  {
    id: 'nhl-3',
    league: 'NHL',
    homeTeam: nhlTeams.rangers_nhl,
    awayTeam: nhlTeams.bruins,
    date: '2024-12-19',
    time: '7:30 PM ET',
    status: 'final',
    homeScore: 4,
    awayScore: 2,
    homeWinProbability: 0.53,
    homeRecentForm: 'WWWWL',
    awayRecentForm: 'WWWLW',
    keyTrend: 'Rangers Shesterkin save% of .935 top-5 in league',
    venue: 'Madison Square Garden',
  },
  {
    id: 'nhl-4',
    league: 'NHL',
    homeTeam: nhlTeams.panthers,
    awayTeam: nhlTeams.avalanche,
    date: '2024-12-27',
    time: '7:00 PM ET',
    status: 'upcoming',
    homeWinProbability: 0.51,
    homeRecentForm: 'WLWWW',
    awayRecentForm: 'WLWWL',
    keyTrend: 'Panthers defending their Stanley Cup title at home (12-4)',
    venue: 'Amerant Bank Arena',
  },
  {
    id: 'nhl-5',
    league: 'NHL',
    homeTeam: nhlTeams.oilers,
    awayTeam: nhlTeams.rangers_nhl,
    date: '2024-12-28',
    time: '9:30 PM ET',
    status: 'upcoming',
    homeWinProbability: 0.56,
    homeRecentForm: 'WWLWW',
    awayRecentForm: 'WWWWL',
    keyTrend: 'McDavid on pace for 140+ point season',
    venue: 'Rogers Place',
  },
  // Soccer
  {
    id: 'soccer-1',
    league: 'Soccer',
    homeTeam: soccerTeams.manCity,
    awayTeam: soccerTeams.arsenal,
    date: '2024-12-21',
    time: '12:30 PM ET',
    status: 'live',
    homeScore: 1,
    awayScore: 1,
    homeWinProbability: 0.52,
    homeRecentForm: 'WWWLW',
    awayRecentForm: 'WWWWL',
    keyTrend: 'Man City unbeaten in last 14 Premier League home games',
    venue: 'Etihad Stadium',
  },
  {
    id: 'soccer-2',
    league: 'Soccer',
    homeTeam: soccerTeams.liverpool,
    awayTeam: soccerTeams.chelsea,
    date: '2024-12-22',
    time: '2:30 PM ET',
    status: 'upcoming',
    homeWinProbability: 0.61,
    homeRecentForm: 'WWWWL',
    awayRecentForm: 'WLLWW',
    keyTrend: 'Liverpool have scored in last 23 home PL matches',
    venue: 'Anfield',
  },
  {
    id: 'soccer-3',
    league: 'Soccer',
    homeTeam: soccerTeams.realMadrid,
    awayTeam: soccerTeams.barcelona,
    date: '2024-12-28',
    time: '3:00 PM ET',
    status: 'upcoming',
    homeWinProbability: 0.48,
    homeRecentForm: 'WWWWW',
    awayRecentForm: 'WWWLW',
    keyTrend: 'El Clásico – Vinicius Jr. has 5 goals in last 3 Clásicos',
    venue: 'Santiago Bernabéu',
  },
  {
    id: 'soccer-4',
    league: 'Soccer',
    homeTeam: soccerTeams.arsenal,
    awayTeam: soccerTeams.liverpool,
    date: '2024-12-15',
    time: '10:00 AM ET',
    status: 'final',
    homeScore: 2,
    awayScore: 2,
    homeWinProbability: 0.44,
    homeRecentForm: 'WWWWL',
    awayRecentForm: 'WWWWL',
    keyTrend: 'Arsenal vs Liverpool draws in 3 of last 4 meetings',
    venue: 'Emirates Stadium',
  },
  {
    id: 'soccer-5',
    league: 'Soccer',
    homeTeam: soccerTeams.barcelona,
    awayTeam: soccerTeams.manCity,
    date: '2024-12-10',
    time: '3:00 PM ET',
    status: 'final',
    homeScore: 3,
    awayScore: 2,
    homeWinProbability: 0.5,
    homeRecentForm: 'WWWLW',
    awayRecentForm: 'WWWLW',
    keyTrend: 'UCL knockout round preview – Lewandowski brace sealed it',
    venue: 'Spotify Camp Nou',
  },
];

// ─── Analysts ────────────────────────────────────────────────────────────────

export const mockAnalysts: Analyst[] = [
  {
    id: 'analyst-1',
    name: 'Marcus Rivera',
    bio: 'NFL specialist with 8 years of professional handicapping experience. Former sports journalist turned full-time analyst.',
    leagues: ['NFL', 'NBA'],
    followers: 48200,
    totalPicks: 892,
    winRate: 0.647,
    performanceScore: 94.2,
    recentRecord: '18-7',
    badges: ['🏆 Top Analyst', '🔥 Hot Streak', '⭐ Verified'],
    isFollowing: true,
  },
  {
    id: 'analyst-2',
    name: 'Sarah Chen',
    bio: 'Data-driven MLB & NHL analyst. Advanced statistics enthusiast. Former baseball operations consultant.',
    leagues: ['MLB', 'NHL'],
    followers: 32100,
    totalPicks: 1204,
    winRate: 0.621,
    performanceScore: 88.7,
    recentRecord: '15-9',
    badges: ['📊 Data Master', '⭐ Verified'],
    isFollowing: false,
  },
  {
    id: 'analyst-3',
    name: 'DeShawn Williams',
    bio: 'NBA expert covering player props, totals, and spread plays. Background in sports psychology.',
    leagues: ['NBA'],
    followers: 61400,
    totalPicks: 743,
    winRate: 0.638,
    performanceScore: 91.5,
    recentRecord: '20-11',
    badges: ['🏀 NBA Guru', '🔥 Hot Streak', '⭐ Verified'],
    isFollowing: true,
  },
  {
    id: 'analyst-4',
    name: 'Priya Nair',
    bio: 'Soccer analytics specialist. Covers Premier League, La Liga, UCL. Statistical modeling expert.',
    leagues: ['Soccer'],
    followers: 27800,
    totalPicks: 658,
    winRate: 0.603,
    performanceScore: 82.3,
    recentRecord: '12-8',
    badges: ['⚽ Soccer Expert'],
    isFollowing: false,
  },
  {
    id: 'analyst-5',
    name: 'Jake Thompson',
    bio: 'Multi-sport analyst specializing in trends, situational betting, and line movement.',
    leagues: ['NFL', 'NBA', 'MLB'],
    followers: 39600,
    totalPicks: 1567,
    winRate: 0.589,
    performanceScore: 79.8,
    recentRecord: '14-10',
    badges: ['🌐 Multi-Sport', '⭐ Verified'],
    isFollowing: false,
  },
  {
    id: 'analyst-6',
    name: 'Elena Kozlov',
    bio: 'NHL analytics powerhouse. Former hockey coach turned data analyst. Power play and goaltending specialist.',
    leagues: ['NHL'],
    followers: 18900,
    totalPicks: 445,
    winRate: 0.612,
    performanceScore: 84.6,
    recentRecord: '11-7',
    badges: ['🏒 Puck Expert'],
    isFollowing: false,
  },
  {
    id: 'analyst-7',
    name: 'Tyrone Jackson',
    bio: 'NFL and CFB specialist. Former college football coach. Offensive scheme and matchup analyst.',
    leagues: ['NFL'],
    followers: 55100,
    totalPicks: 923,
    winRate: 0.631,
    performanceScore: 89.9,
    recentRecord: '17-9',
    badges: ['🏈 Gridiron Pro', '⭐ Verified'],
    isFollowing: true,
  },
  {
    id: 'analyst-8',
    name: 'Mei Zhang',
    bio: 'Quantitative sports analyst. Machine learning models applied to sports prediction. MIT grad.',
    leagues: ['NFL', 'NBA', 'MLB', 'NHL', 'Soccer'],
    followers: 44700,
    totalPicks: 2103,
    winRate: 0.574,
    performanceScore: 76.2,
    recentRecord: '16-12',
    badges: ['🤖 AI Analyst', '🌐 Multi-Sport'],
    isFollowing: false,
  },
  {
    id: 'analyst-9',
    name: 'Carlos Mendez',
    bio: 'MLB and Soccer expert. Former semi-pro baseball player. Covers Latin American leagues.',
    leagues: ['MLB', 'Soccer'],
    followers: 21300,
    totalPicks: 834,
    winRate: 0.595,
    performanceScore: 80.1,
    recentRecord: '13-9',
    badges: ['⚾ Diamond Pro', '⚽ Soccer Expert'],
    isFollowing: false,
  },
  {
    id: 'analyst-10',
    name: 'Ashley Brooks',
    bio: 'Rising star in sports analytics. Known for contrarian picks and upset predictions. 2023 Rookie Analyst of the Year.',
    leagues: ['NBA', 'Soccer'],
    followers: 29500,
    totalPicks: 312,
    winRate: 0.654,
    performanceScore: 93.1,
    recentRecord: '21-11',
    badges: ['🌟 Rising Star', '🔥 Hot Streak'],
    isFollowing: false,
  },
];

// ─── Picks ────────────────────────────────────────────────────────────────────

export const mockPicks: Pick[] = [
  {
    id: 'pick-1',
    analystId: 'analyst-1',
    analystName: 'Marcus Rivera',
    league: 'NFL',
    game: 'KC Chiefs vs BAL Ravens',
    pick: 'Chiefs -3.5',
    confidence: 82,
    reasoning: 'Mahomes at home in a divisional-style matchup. Ravens secondary has been susceptible to play-action and Kelce is at full health. Historical edge for KC in prime-time games.',
    result: 'pending',
    likes: 341,
    comments: 47,
    timestamp: '2024-12-21T10:30:00Z',
    isLiked: true,
  },
  {
    id: 'pick-2',
    analystId: 'analyst-3',
    analystName: 'DeShawn Williams',
    league: 'NBA',
    game: 'BOS Celtics vs DEN Nuggets',
    pick: 'Celtics -4.5',
    confidence: 76,
    reasoning: 'Boston home court advantage is massive this year. Jokic tends to struggle against physical big men and Al Horford plays excellent help defense. Celtics 3PT shooting should carry the day.',
    result: 'win',
    likes: 287,
    comments: 38,
    timestamp: '2024-12-20T18:45:00Z',
    isLiked: false,
  },
  {
    id: 'pick-3',
    analystId: 'analyst-7',
    analystName: 'Tyrone Jackson',
    league: 'NFL',
    game: 'PHI Eagles vs DAL Cowboys',
    pick: 'Eagles -7',
    confidence: 88,
    reasoning: 'Eagles dominant at home this season. Cowboys missing two starting offensive linemen. Hurts has 14 TD with 2 INT at home. Line movement confirms sharp money on Philly.',
    result: 'win',
    likes: 512,
    comments: 64,
    timestamp: '2024-12-19T14:00:00Z',
    isLiked: true,
  },
  {
    id: 'pick-4',
    analystId: 'analyst-2',
    analystName: 'Sarah Chen',
    league: 'NHL',
    game: 'BOS Bruins vs FLA Panthers',
    pick: 'Bruins ML',
    confidence: 71,
    reasoning: 'Bruins power play clicking at 28.4% this week. Panthers on back-to-back away from home. Swayman has .940 SV% in last 5 home starts.',
    result: 'pending',
    likes: 178,
    comments: 22,
    timestamp: '2024-12-21T12:15:00Z',
    isLiked: false,
  },
  {
    id: 'pick-5',
    analystId: 'analyst-4',
    analystName: 'Priya Nair',
    league: 'Soccer',
    game: 'MCI Man City vs ARS Arsenal',
    pick: 'Draw +185',
    confidence: 65,
    reasoning: 'Arsenal have shown they can hold Man City at Etihad. Both teams come in fatigued from midweek UCL fixtures. Historical tendency for low-scoring affairs at Etihad when Arsenal visit.',
    result: 'win',
    likes: 423,
    comments: 89,
    timestamp: '2024-12-20T09:00:00Z',
    isLiked: false,
  },
  {
    id: 'pick-6',
    analystId: 'analyst-10',
    analystName: 'Ashley Brooks',
    league: 'NBA',
    game: 'OKC Thunder vs LAL Lakers',
    pick: 'Thunder -9',
    confidence: 91,
    reasoning: 'SGA is unstoppable at home. Lakers missing Davis (questionable) and the backcourt defense is giving up 118+ points per game. OKC has won 8 of last 9 at home by double digits.',
    result: 'win',
    likes: 634,
    comments: 97,
    timestamp: '2024-12-21T16:00:00Z',
    isLiked: true,
  },
  {
    id: 'pick-7',
    analystId: 'analyst-5',
    analystName: 'Jake Thompson',
    league: 'MLB',
    game: 'LAD Dodgers vs NYY Yankees',
    pick: 'Dodgers -1.5',
    confidence: 78,
    reasoning: 'Dodgers starters ERA under 2.50 in playoffs. Their lineup depth is unmatched. Yankees bullpen has been stretched thin.',
    result: 'win',
    likes: 298,
    comments: 41,
    timestamp: '2024-12-18T11:30:00Z',
    isLiked: false,
  },
  {
    id: 'pick-8',
    analystId: 'analyst-1',
    analystName: 'Marcus Rivera',
    league: 'NFL',
    game: 'SF 49ers vs BUF Bills',
    pick: '49ers -2',
    confidence: 74,
    reasoning: 'Purdy hot streak continues. Bills secondary banged up. 49ers versatile offense hard to defend.',
    result: 'win',
    likes: 445,
    comments: 58,
    timestamp: '2024-12-18T09:45:00Z',
    isLiked: false,
  },
  {
    id: 'pick-9',
    analystId: 'analyst-6',
    analystName: 'Elena Kozlov',
    league: 'NHL',
    game: 'NYR Rangers vs BOS Bruins',
    pick: 'Rangers ML',
    confidence: 69,
    reasoning: 'MSG crowd factor is huge. Shesterkin elite at home. Bruins on 3rd game in 4 nights.',
    result: 'win',
    likes: 156,
    comments: 19,
    timestamp: '2024-12-17T16:30:00Z',
    isLiked: false,
  },
  {
    id: 'pick-10',
    analystId: 'analyst-9',
    analystName: 'Carlos Mendez',
    league: 'Soccer',
    game: 'ARS Arsenal vs LIV Liverpool',
    pick: 'Both Teams to Score',
    confidence: 83,
    reasoning: 'Both clubs have scored in last 10 EPL matches. Arsenal and Liverpool both prefer high-press attacking styles. Expected goals models favor at least 2.8 total goals.',
    result: 'push',
    likes: 267,
    comments: 33,
    timestamp: '2024-12-15T08:00:00Z',
    isLiked: false,
  },
  {
    id: 'pick-11',
    analystId: 'analyst-3',
    analystName: 'DeShawn Williams',
    league: 'NBA',
    game: 'MIL Bucks vs MIA Heat',
    pick: 'Bucks -7.5',
    confidence: 85,
    reasoning: 'Giannis health status confirmed. Heat missing Herro and Butler (out). Bucks dominant at home when fully healthy with Giannis.',
    result: 'win',
    likes: 389,
    comments: 52,
    timestamp: '2024-12-19T20:00:00Z',
    isLiked: true,
  },
  {
    id: 'pick-12',
    analystId: 'analyst-8',
    analystName: 'Mei Zhang',
    league: 'NFL',
    game: 'KC Chiefs vs BUF Bills',
    pick: 'Chiefs ML',
    confidence: 72,
    reasoning: 'Model outputs 61.2% win probability for Chiefs. Home field, rest advantage, and red zone efficiency heavily favor Kansas City.',
    result: 'win',
    likes: 201,
    comments: 28,
    timestamp: '2024-12-14T13:00:00Z',
    isLiked: false,
  },
  {
    id: 'pick-13',
    analystId: 'analyst-2',
    analystName: 'Sarah Chen',
    league: 'MLB',
    game: 'HOU Astros vs ATL Braves',
    pick: 'Astros -1.5',
    confidence: 67,
    reasoning: 'Astros bullpen has been elite. Braves starter not sharp in last two outings.',
    result: 'win',
    likes: 143,
    comments: 17,
    timestamp: '2024-12-13T10:00:00Z',
    isLiked: false,
  },
  {
    id: 'pick-14',
    analystId: 'analyst-4',
    analystName: 'Priya Nair',
    league: 'Soccer',
    game: 'FCB Barcelona vs MCI Man City',
    pick: 'Barcelona +110',
    confidence: 70,
    reasoning: 'Barca at Camp Nou is a different animal. Lewandowski in scoring form. Man City fatigue from domestic schedule.',
    result: 'win',
    likes: 334,
    comments: 61,
    timestamp: '2024-12-10T07:30:00Z',
    isLiked: false,
  },
  {
    id: 'pick-15',
    analystId: 'analyst-7',
    analystName: 'Tyrone Jackson',
    league: 'NFL',
    game: 'BAL Ravens vs SF 49ers',
    pick: 'Ravens -3',
    confidence: 79,
    reasoning: 'Ravens home field edge massive. Lamar MVP campaign in full swing. 49ers secondary struggles against mobile QBs.',
    result: 'pending',
    likes: 478,
    comments: 73,
    timestamp: '2024-12-21T11:00:00Z',
    isLiked: false,
  },
  {
    id: 'pick-16',
    analystId: 'analyst-10',
    analystName: 'Ashley Brooks',
    league: 'Soccer',
    game: 'LIV Liverpool vs CHE Chelsea',
    pick: 'Liverpool -1',
    confidence: 86,
    reasoning: 'Anfield fortress. Liverpool scoring 3+ goals in 7 of last 10 home games. Chelsea defensive issues persist.',
    result: 'pending',
    likes: 521,
    comments: 84,
    timestamp: '2024-12-21T14:00:00Z',
    isLiked: true,
  },
  {
    id: 'pick-17',
    analystId: 'analyst-5',
    analystName: 'Jake Thompson',
    league: 'NBA',
    game: 'DEN Nuggets vs MIL Bucks',
    pick: 'Over 225.5',
    confidence: 73,
    reasoning: 'Nuggets and Bucks both prefer up-tempo offense. Combined scoring average over 230 in last 5 matchups. Neither team has elite perimeter defense.',
    result: 'pending',
    likes: 167,
    comments: 24,
    timestamp: '2024-12-21T17:30:00Z',
    isLiked: false,
  },
  {
    id: 'pick-18',
    analystId: 'analyst-1',
    analystName: 'Marcus Rivera',
    league: 'NFL',
    game: 'BAL Ravens vs SF 49ers',
    pick: 'Ravens ML',
    confidence: 77,
    reasoning: 'Critical divisional positioning on the line. Ravens defense elite at home – limiting opposing QBs to 61.2% completion rate.',
    result: 'pending',
    likes: 392,
    comments: 55,
    timestamp: '2024-12-21T09:00:00Z',
    isLiked: false,
  },
  {
    id: 'pick-19',
    analystId: 'analyst-6',
    analystName: 'Elena Kozlov',
    league: 'NHL',
    game: 'COL Avalanche vs EDM Oilers',
    pick: 'Over 6.5',
    confidence: 80,
    reasoning: 'Both teams have elite offensive firepower. MacKinnon and McDavid matchup guarantees fireworks. Both starting goalies have allowed 3+ goals in 4 straight.',
    result: 'pending',
    likes: 213,
    comments: 31,
    timestamp: '2024-12-21T18:00:00Z',
    isLiked: false,
  },
  {
    id: 'pick-20',
    analystId: 'analyst-8',
    analystName: 'Mei Zhang',
    league: 'NBA',
    game: 'LAL Lakers vs BOS Celtics',
    pick: 'Celtics -7.5',
    confidence: 88,
    reasoning: 'Model gives Celtics 71.4% win probability on the road. Lakers 3-9 SU at home vs top-5 defensive teams this season.',
    result: 'loss',
    likes: 189,
    comments: 27,
    timestamp: '2024-12-12T14:00:00Z',
    isLiked: false,
  },
];

// ─── Leaderboard ──────────────────────────────────────────────────────────────

export const mockLeaderboard: LeaderboardEntry[] = [
  { rank: 1, previousRank: 2, analyst: mockAnalysts[9], accuracy: 0.654, totalPicks: 312, recentRecord: '21-11', followers: 29500 },
  { rank: 2, previousRank: 1, analyst: mockAnalysts[0], accuracy: 0.647, totalPicks: 892, recentRecord: '18-7', followers: 48200 },
  { rank: 3, previousRank: 3, analyst: mockAnalysts[2], accuracy: 0.638, totalPicks: 743, recentRecord: '20-11', followers: 61400 },
  { rank: 4, previousRank: 6, analyst: mockAnalysts[6], accuracy: 0.631, totalPicks: 923, recentRecord: '17-9', followers: 55100 },
  { rank: 5, previousRank: 4, analyst: mockAnalysts[1], accuracy: 0.621, totalPicks: 1204, recentRecord: '15-9', followers: 32100 },
  { rank: 6, previousRank: 5, analyst: mockAnalysts[5], accuracy: 0.612, totalPicks: 445, recentRecord: '11-7', followers: 18900 },
  { rank: 7, previousRank: 7, analyst: mockAnalysts[3], accuracy: 0.603, totalPicks: 658, recentRecord: '12-8', followers: 27800 },
  { rank: 8, previousRank: 9, analyst: mockAnalysts[8], accuracy: 0.595, totalPicks: 834, recentRecord: '13-9', followers: 21300 },
  { rank: 9, previousRank: 8, analyst: mockAnalysts[4], accuracy: 0.589, totalPicks: 1567, recentRecord: '14-10', followers: 39600 },
  { rank: 10, previousRank: 10, analyst: mockAnalysts[7], accuracy: 0.574, totalPicks: 2103, recentRecord: '16-12', followers: 44700 },
];

// ─── Community Posts ──────────────────────────────────────────────────────────

export const mockPosts: Post[] = [
  {
    id: 'post-1',
    authorId: 'user-1',
    authorName: 'GridironGuru99',
    topic: 'AFC Championship Predictions',
    content: 'Ravens vs Chiefs in January feels inevitable. Both teams playing elite football. Lamar vs Mahomes round 4 is going to be must-watch TV. Who are you backing?',
    league: 'NFL',
    timestamp: '2024-12-21T11:30:00Z',
    commentCount: 47,
    likes: 234,
  },
  {
    id: 'post-2',
    authorId: 'user-2',
    authorName: 'NBAStats_Nerd',
    topic: 'SGA MVP Case',
    content: 'Can we talk about how SGA is building an MVP case? 32.4 PPG, 49% FG, leading OKC to 26-9. Celtics fans will argue Tatum but the numbers don\'t lie.',
    league: 'NBA',
    timestamp: '2024-12-21T10:00:00Z',
    commentCount: 83,
    likes: 412,
  },
  {
    id: 'post-3',
    authorId: 'user-3',
    authorName: 'PuckheadPete',
    topic: 'Shesterkin for Hart?',
    content: 'Shesterkin at .935 SV% and Rangers sitting atop the Metropolitan division. The Hart Trophy conversation needs to include goalies again – what do you guys think?',
    league: 'NHL',
    timestamp: '2024-12-20T19:45:00Z',
    commentCount: 31,
    likes: 178,
  },
  {
    id: 'post-4',
    authorId: 'user-4',
    authorName: 'ElClasico_Fan',
    topic: 'Real Madrid vs Barcelona Preview',
    content: 'El Clásico next weekend and both squads are in top form. Vinicius Jr. has been absolutely unplayable this season. Anyone backing Barcelona at the Bernabéu?',
    league: 'Soccer',
    timestamp: '2024-12-21T08:15:00Z',
    commentCount: 122,
    likes: 567,
  },
  {
    id: 'post-5',
    authorId: 'user-5',
    authorName: 'BaseballBrain',
    topic: 'Ohtani Era Begins',
    content: 'Two-way star Shohei Ohtani is redefining what\'s possible in baseball. The Dodgers are set up to dominate for the next decade. Scary for the rest of the NL.',
    league: 'MLB',
    timestamp: '2024-12-19T14:30:00Z',
    commentCount: 56,
    likes: 309,
  },
  {
    id: 'post-6',
    authorId: 'user-6',
    authorName: 'LineMovementLarry',
    topic: 'Sharp Action Alert',
    content: 'Heavy sharp action coming in on Ravens ML for Sunday. Line opened -1.5 and is now -3.5. Follow the money, not the public. Public is 73% on Chiefs.',
    league: 'NFL',
    timestamp: '2024-12-21T09:30:00Z',
    commentCount: 68,
    likes: 445,
  },
  {
    id: 'post-7',
    authorId: 'user-7',
    authorName: 'xGQueen',
    topic: 'ManCity vs Arsenal xG Battle',
    content: 'The tactical battle between Guardiola and Arteta today is a chess match. Arsenal\'s high press vs City\'s positional play. xG models are split 50/50 – classic.',
    league: 'Soccer',
    timestamp: '2024-12-21T11:00:00Z',
    commentCount: 94,
    likes: 389,
  },
  {
    id: 'post-8',
    authorId: 'user-8',
    authorName: 'CelticsBanner18',
    topic: 'Celtics Dynasty Watch',
    content: 'Celtics at 28-7 with the best net rating in the league. Defensive powerhouse + Tatum/Brown development = Banner 18 very much in play. Don\'t sleep on Boston.',
    league: 'NBA',
    timestamp: '2024-12-20T21:00:00Z',
    commentCount: 72,
    likes: 356,
  },
  {
    id: 'post-9',
    authorId: 'user-9',
    authorName: 'HockeyHeatFan',
    topic: 'Panthers Back-to-Back?',
    content: 'Florida Panthers looking to repeat as Stanley Cup champs. Their system is built for playoff hockey. Bobrovsky looks sharp and the top 6 is fully healthy.',
    league: 'NHL',
    timestamp: '2024-12-19T17:00:00Z',
    commentCount: 28,
    likes: 143,
  },
  {
    id: 'post-10',
    authorId: 'user-10',
    authorName: 'SportsAnalyticsGeek',
    topic: 'Best Analytics Resources',
    content: 'What are your go-to advanced stats sites? I use PFF for NFL, Cleaning the Glass for NBA, Baseball Savant for MLB, Natural Stat Trick for NHL. What am I missing?',
    league: 'General',
    timestamp: '2024-12-18T12:00:00Z',
    commentCount: 49,
    likes: 201,
  },
  {
    id: 'post-11',
    authorId: 'user-11',
    authorName: 'DodgerFaithful',
    topic: 'Dodgers Offseason Moves',
    content: 'Dodgers adding more pieces this offseason after their World Series run. The pitching depth is insane and Ohtani + Betts + Freeman is a generational lineup.',
    league: 'MLB',
    timestamp: '2024-12-17T10:30:00Z',
    commentCount: 38,
    likes: 267,
  },
  {
    id: 'post-12',
    authorId: 'user-12',
    authorName: 'PropBetProfessor',
    topic: 'Top Player Props This Week',
    content: 'Loving Lamar Jackson over 280.5 passing yards this week. Ravens will need to throw against SF\'s run defense. Also like Tatum over 27.5 points vs Nuggets.',
    league: 'General',
    timestamp: '2024-12-21T07:00:00Z',
    commentCount: 57,
    likes: 334,
  },
  {
    id: 'post-13',
    authorId: 'user-13',
    authorName: 'McDavidMagic',
    topic: 'McDavid 140 Point Season',
    content: 'If McDavid hits 140 points this season it would be the highest total since Lemieux in 1996. We are watching the greatest offensive player in hockey history right now.',
    league: 'NHL',
    timestamp: '2024-12-20T16:00:00Z',
    commentCount: 45,
    likes: 289,
  },
  {
    id: 'post-14',
    authorId: 'user-14',
    authorName: 'TailgateVet',
    topic: 'NFL Playoff Picture',
    content: 'AFC playoff picture: Chiefs, Ravens, Bills, Steelers in. Wild card fight between Bengals, Colts, and Broncos. NFC: Eagles, Lions, Vikings, Rams all looking strong.',
    league: 'NFL',
    timestamp: '2024-12-21T13:00:00Z',
    commentCount: 91,
    likes: 478,
  },
  {
    id: 'post-15',
    authorId: 'user-15',
    authorName: 'BetingBanker',
    topic: 'Bankroll Management Tips',
    content: 'Reminder to everyone: never bet more than 3-5% of your bankroll on a single game. Even the best analysts have cold streaks. Protect the bag, grind the process.',
    league: 'General',
    timestamp: '2024-12-20T09:00:00Z',
    commentCount: 34,
    likes: 512,
  },
];
